### ISSUE TITLE
I tryed you Demo App and get errors

### ISSUE THREAD

**Issue by marcus7777** [EveryBit-com/everybit.js#172]
"Uncaught ReferenceError: EB is not defined" in Chrome
"ReferenceError: EB is not defined" in Iceweasel 

And not Working can you help?

**Comment by arafeek** [comment]
Thanks for pointing this out. If you pull now everything should be fine.

**Comment by marcus7777** [comment]
Thank you Great Stuff Love This Project

**Comment by marcus7777** [comment]
Confirmed Works Great
